name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Stable rustc
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build docs
        run: cargo doc --lib
      - uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: ./target/doc
          clean: true
