[package]
name = "axum-0"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "=0.7.5"
reqwest = { version = "0.12", features = ["stream"] }
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
tower-http = { version = "0.5.0", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
