name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64, aarch64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build Image (${{ matrix.arch }})
        run: |
          nix build
          cp result pldi-argus-${{ matrix.arch }}.tar.gz

