name: release

on:
  push:
    branch: 
      - "main"
    #tags: "v*.*.*"

jobs:
  build-and-release:
    name: Build and Release
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
            output_name: amd64
          - os: ['self-hosted', 'ARM64']
            arch: aarch64
            output_name: arm64
    runs-on: ${{ matrix.os }}
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/pldi25-argus-${{ matrix.output_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Build Docker Image
        run: nix build . --verbose --show-trace --print-build-logs

      - name: Export Docker Image
        run: |
          cp -L result "$IMAGE_NAME.tar.gz"
          nix develop . --verbose --show-trace --print-build-logs --command publish-image "$IMAGE_NAME" ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
