name: release

on:
  push:
    branch: 
      - "main"
    #tags: "v*.*.*"

jobs:
  build-and-release:
    name: Build and Release
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
            output_name: amd64
          - os: ['self-hosted', 'ARM64']
            arch: aarch64
            output_name: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Check Docker Config
        run: |
          echo "Current user: $(whoami)"
          ls -la ~/.docker
          cat ~/.docker/config.json || echo "No config.json found"

      # For debugging
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        env:
          DOCKER_PWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: nix build . --option sandbox false

      - name: Export Docker Image
        run: |
          cp -L result pldi25-argus-${{ matrix.output_name }}.tar.gz
          nix develop . --command publish-image pldi25-argus-${{ matrix.output_name }} ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_PASSWORD }}
      #
      # - name: Publish Release Artifact
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: pldi25-argus-${{ matrix.output_name }}.tar.gz
