name: release

on:
  push:
    tags: "v*"

jobs:
  build-and-release:
    name: Build and Release
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            output_name: amd64
          - os: ubuntu-22.04-arm
            output_name: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}

      - name: Build Docker Image
        run: |
          nix build . -L
          cp -L result pldi25-argus-${{ matrix.output_name }}.tar.gz
          nix store gc

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish Docker Image
        run: |
          docker image < pldi25-argus-${{ matrix.output_name }}.tar.gz
          docker push gavinleroy/pldi25-argus-${{ matrix.output_name }}:latest

      - name: Publish Release Artifact
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pldi25-argus-${{ matrix.output_name }}.tar.gz
