name: release

on:
  push:
    tags: "v*"

jobs:
  build-and-release:
    name: Build and Release
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            output_name: amd64
          - os: ubuntu-22.04-arm
            output_name: aarch64
    runs-on: ${{ matrix.os }}
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/pldi25-argus-${{ matrix.output_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}

      - name: Build Docker Image
        run: nix build . -L

      - name: Export Docker Image
        run: |
          cp -L result "$IMAGE_NAME.tar.gz"
          docker load < "$IMAGE_NAME.tar.gz"
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push "$IMAGE_NAME"

      - name: Publish Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
