name: test

on:
  push:
    branch: "main"

jobs:
  build-and-release:
    name: Test Build
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            output_name: amd64
          - os: ubuntu-22.04-arm
            output_name: aarch64
    runs-on: ${{ matrix.os }}
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/pldi25-argus-${{ matrix.output_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/cachix-action@v16
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build Docker Image
        timeout-minutes: 45
        run: nix build . -L
